# Unendliches Übungsblatt zur Matrix-Matrix-Multiplikation
_zum Kapitel 8.2 im Kurs MH2 im WS20_

### Zweck
Mit diesem Notebook soll (etwas stupide) das Matrix-Matrix-Produkt geübt werden:
$$A \cdot B$$

### Anleitung
* Um neue Aufgaben zu generieren: `Cell` $\rightarrow$ `Run all` im Menü wählen
* Sie können in der erste Zelle die Anzahl der Aufgaben, maximale Spalten- und Zeilenanzahl sowie den Bereich der möglichen Zahlenwerte verändern
* Die Aufgaben erscheinen als Ausgabe der 2. Zelle, die Lösung als Ausgabe der 3. Zelle darunter
* Die Formatierung der Matrizen ist mit den vielen eckigen Klammern etwas unschön, aber ich denke verständlich...

In [1]:
# Wieviel Aufgaben wollen Sie?
Anzahl = 3

# hier kann man maximale Spalten- bzw. Zeilenzahl (n) der Matrizen festlegen
max_dim = 3 # sollte > 1 sein

# Bereich der Zahlenwerte in der Aufgabe?
min_zahl = -5  # Wollen Sie keine negativen Zahlen, setzen Sie diesen Wert auf 0
max_zahl = +5

In [2]:
# ab hier nix verändern
import numpy as np

Loesungen = []
for k in range(Anzahl):
    print('Aufgabe Nr.', k+1)
    
    n = np.random.randint(2, max_dim+1)
    m = np.random.randint(2, max_dim+1)
    k = np.random.randint(2, max_dim+1)
    
    A = np.random.randint(min_zahl,max_zahl,[n,m])
    B = np.random.randint(min_zahl,max_zahl,[m,k])
    
    Loesungen.append(np.matmul(A,B))
    print(' Matrix A:')
    print('', A)

    print(' Matrix B:')
    print('',B)
    print('----------------')

Aufgabe Nr. 1
 Matrix A:
 [[-5  2  1]
 [ 1  0  1]
 [-2  4  4]]
 Matrix B:
 [[-2 -1]
 [-4 -4]
 [-3 -2]]
----------------
Aufgabe Nr. 2
 Matrix A:
 [[ 2  2]
 [ 1  3]
 [ 0 -5]]
 Matrix B:
 [[ 3 -5 -3]
 [ 0  1  3]]
----------------
Aufgabe Nr. 3
 Matrix A:
 [[ 3 -4  4]
 [ 1 -3  0]]
 Matrix B:
 [[-5  3]
 [-3 -5]
 [-4 -4]]
----------------


## Lösungen

In [3]:
for k in range(Anzahl):
    print('Lösung zu Aufgabe Nr.', k+1)
    print(' A*B =')
    print('', Loesungen[k])
    print('----------------')

Lösung zu Aufgabe Nr. 1
 A*B =
 [[ -1  -5]
 [ -5  -3]
 [-24 -22]]
----------------
Lösung zu Aufgabe Nr. 2
 A*B =
 [[  6  -8   0]
 [  3  -2   6]
 [  0  -5 -15]]
----------------
Lösung zu Aufgabe Nr. 3
 A*B =
 [[-19  13]
 [  4  18]]
----------------
