# Unendliches Übungsblatt zur Matrix-Vektor-Multiplikation
_zum Kapitel 8.2 im Kurs MH2 im WS20_

### Zweck
Mit diesem Notebook soll (etwas stupide) das Matrix-Vektor-Produkt geübt werden:
$$A \cdot \vec x$$

### Anleitung
* Um neue Aufgaben zu generieren: `Cell` $\rightarrow$ `Run all` im Menü wählen
* Sie können in der erste Zelle die Anzahl der Aufgaben, maximale Spalten- und Zeilenanzahl sowie den Bereich der möglichen Zahlenwerte verändern
* Die Aufgaben erscheinen als Ausgabe der 2. Zelle, die Lösung als Ausgabe der 3. Zelle darunter
* Die Formatierung von Matrix und Vektor ist mit den vielen eckigen Klammern etwas unschön, aber ich denke verständlich...

In [10]:
# Wieviel Aufgaben wollen Sie?
Anzahl = 3

# hier kann man maximale Spalten- (m) und Zeilenzahl (n) der Matrix festlegen
max_m = 4 # sollte > 1 sein
max_n = 4 # sollte > 1 sein

# Bereich der Zahlenwerte in der Aufgabe?
min_zahl = -5  # Wollen Sie keine negativen Zahlen, setzen Sie diesen Wert auf 0
max_zahl = +5

In [11]:
# ab hier nix verändern
import numpy as np

Loesungen = []
for k in range(Anzahl):
    print('Aufgabe Nr.', k+1)
    
    n = np.random.randint(2, max_n+1)
    m = np.random.randint(2, max_m+1)
    A = np.random.randint(min_zahl,max_zahl,[n,m])
    x = np.random.randint(min_zahl,max_zahl,[m,1])
    
    Loesungen.append(np.matmul(A,x))
    print(' Matrix A:')
    print('', A)

    print(' Vektor x:')
    print('',x)
    print('----------------')

Aufgabe Nr. 1
 Matrix A:
 [[-2  3 -2 -3]
 [ 3 -3  0 -4]
 [ 0  3  2  0]
 [ 1 -4 -5 -1]]
 Vektor x:
 [[1]
 [4]
 [2]
 [2]]
----------------
Aufgabe Nr. 2
 Matrix A:
 [[ 2  0 -1  3]
 [-4 -4  1 -1]
 [ 1  1  3 -5]]
 Vektor x:
 [[-1]
 [-3]
 [-4]
 [-3]]
----------------
Aufgabe Nr. 3
 Matrix A:
 [[-1  0]
 [ 0  4]]
 Vektor x:
 [[1]
 [4]]
----------------


## Lösungen

In [12]:
for k in range(Anzahl):
    print('Lösung zu Aufgabe Nr.', k+1)
    print(' A*x =')
    print('', Loesungen[k])
    print('----------------')

Lösung zu Aufgabe Nr. 1
 A*x =
 [[  0]
 [-17]
 [ 16]
 [-27]]
----------------
Lösung zu Aufgabe Nr. 2
 A*x =
 [[-7]
 [15]
 [-1]]
----------------
Lösung zu Aufgabe Nr. 3
 A*x =
 [[-1]
 [16]]
----------------
